### ISSUE TITLE
KeyError: 'from'

### ISSUE THREAD

**Issue by antontarasenko** [precognox-admin/FBscraper#1]
Running `python FBscraper/src/scrapeFB.py` with parameters in the command line returns:

```
Traceback (most recent call last):
  File "FBscraper/src/scrapeFB.py", line 325, in <module>
    s.scrape()
  File "FBscraper/src/scrapeFB.py", line 264, in scrape
    self.write_data(d)
  File "FBscraper/src/scrapeFB.py", line 91, in write_data
    person_name = message['from']['name']
KeyError: 'from'
```

The same in other Python versions (2, 3).

**Comment by antontarasenko** [comment]
It was an API issue. The scraper's code needed some fixes.

**Comment by Zer0ne83** [comment]
Yep, got the same issue...
Scraping page 1 of feed id 289457783173
Traceback (most recent call last):
  File "scrapeFB.py", line 325, in <module>
    s.scrape()
  File "scrapeFB.py", line 264, in scrape
    self.write_data(d)
  File "scrapeFB.py", line 91, in write_data
    person_name = message['from']['name']
KeyError: 'from'
(facebookenv) root@kalipi2:~/FBscraper/src#

Is there a fix yet? I just cloned the current repo 10 mins ago and received the same error.

**Comment by antontarasenko** [comment]
I modified `scrapeFB.py` to fix this error:

* https://gist.github.com/antontarasenko/cb94f6ee0e8174beeb576e5974301f8b

It includes other minor changes. `diff` against the original `scrapeFB.py` shows what exactly.

The error was due to the FB API that had stopped returning full responses to save on traffic.

**Comment by lpeter94** [comment]
Thanks for your help. It fixed the keyerror. But "addinfourl instance has no attribue '__exit__' appeared. I tried to fix this error with this:

https://stackoverflow.com/questions/30627937/traceback-attributeerroraddinfourl-instance-has-no-attribute-exit/30628128

but it doesn't worked.
